# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autenticacion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "autenticacion.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import usuario_pb2 as usuario__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x61utenticacion.proto\x12\ncom.grupog\x1a\rusuario.proto"4\n\x0cLoginRequest\x12\x15\n\rnombreUsuario\x18\x01 \x01(\t\x12\r\n\x05\x63lave\x18\x02 \x01(\t"D\n\rLoginResponse\x12$\n\x07usuario\x18\x01 \x01(\x0b\x32\x13.com.grupog.Usuario\x12\r\n\x05token\x18\x02 \x01(\t"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t"\x1f\n\x0eLogoutResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x32\x96\x01\n\x15\x41uthenticationService\x12<\n\x05login\x12\x18.com.grupog.LoginRequest\x1a\x19.com.grupog.LoginResponse\x12?\n\x06logout\x12\x19.com.grupog.LogoutRequest\x1a\x1a.com.grupog.LogoutResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "autenticacion_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LOGINREQUEST"]._serialized_start = 50
    _globals["_LOGINREQUEST"]._serialized_end = 102
    _globals["_LOGINRESPONSE"]._serialized_start = 104
    _globals["_LOGINRESPONSE"]._serialized_end = 172
    _globals["_LOGOUTREQUEST"]._serialized_start = 174
    _globals["_LOGOUTREQUEST"]._serialized_end = 204
    _globals["_LOGOUTRESPONSE"]._serialized_start = 206
    _globals["_LOGOUTRESPONSE"]._serialized_end = 237
    _globals["_AUTHENTICATIONSERVICE"]._serialized_start = 240
    _globals["_AUTHENTICATIONSERVICE"]._serialized_end = 390
# @@protoc_insertion_point(module_scope)
