# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.crearItem = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/crearItem',
                request_serializer=inventario__pb2.CrearItemRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioItem.FromString,
                _registered_method=True)
        self.actualizarItem = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/actualizarItem',
                request_serializer=inventario__pb2.ActualizarItemRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioItem.FromString,
                _registered_method=True)
        self.bajaLogicaItem = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/bajaLogicaItem',
                request_serializer=inventario__pb2.BajaLogicaItemRequest.SerializeToString,
                response_deserializer=inventario__pb2.RespuestaExito.FromString,
                _registered_method=True)
        self.listarItems = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/listarItems',
                request_serializer=inventario__pb2.ListarItemsRequest.SerializeToString,
                response_deserializer=inventario__pb2.ListaItemsResponse.FromString,
                _registered_method=True)
        self.buscarItemPorId = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/buscarItemPorId',
                request_serializer=inventario__pb2.BuscarItemPorIdRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioItem.FromString,
                _registered_method=True)
        self.registrarSalida = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/registrarSalida',
                request_serializer=inventario__pb2.RegistrarSalidaRequest.SerializeToString,
                response_deserializer=inventario__pb2.RespuestaExito.FromString,
                _registered_method=True)
        self.solicitarDonaciones = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/solicitarDonaciones',
                request_serializer=inventario__pb2.SolicitarDonacionesRequest.SerializeToString,
                response_deserializer=inventario__pb2.SolicitarDonacionesResponse.FromString,
                _registered_method=True)
        self.listarSolicitudesExternas = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/listarSolicitudesExternas',
                request_serializer=inventario__pb2.ListarSolicitudesExternasRequest.SerializeToString,
                response_deserializer=inventario__pb2.ListarSolicitudesExternasResponse.FromString,
                _registered_method=True)
        self.transferirDonacion = channel.unary_unary(
                '/com.grupog.inventario.InventarioService/transferirDonacion',
                request_serializer=inventario__pb2.TransferirDonacionRequest.SerializeToString,
                response_deserializer=inventario__pb2.RespuestaExito.FromString,
                _registered_method=True)


class InventarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def crearItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def actualizarItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bajaLogicaItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def buscarItemPorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registrarSalida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def solicitarDonaciones(self, request, context):
        """Kafka - Solicitudes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarSolicitudesExternas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def transferirDonacion(self, request, context):
        """Kafka - Transferencias
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'crearItem': grpc.unary_unary_rpc_method_handler(
                    servicer.crearItem,
                    request_deserializer=inventario__pb2.CrearItemRequest.FromString,
                    response_serializer=inventario__pb2.InventarioItem.SerializeToString,
            ),
            'actualizarItem': grpc.unary_unary_rpc_method_handler(
                    servicer.actualizarItem,
                    request_deserializer=inventario__pb2.ActualizarItemRequest.FromString,
                    response_serializer=inventario__pb2.InventarioItem.SerializeToString,
            ),
            'bajaLogicaItem': grpc.unary_unary_rpc_method_handler(
                    servicer.bajaLogicaItem,
                    request_deserializer=inventario__pb2.BajaLogicaItemRequest.FromString,
                    response_serializer=inventario__pb2.RespuestaExito.SerializeToString,
            ),
            'listarItems': grpc.unary_unary_rpc_method_handler(
                    servicer.listarItems,
                    request_deserializer=inventario__pb2.ListarItemsRequest.FromString,
                    response_serializer=inventario__pb2.ListaItemsResponse.SerializeToString,
            ),
            'buscarItemPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.buscarItemPorId,
                    request_deserializer=inventario__pb2.BuscarItemPorIdRequest.FromString,
                    response_serializer=inventario__pb2.InventarioItem.SerializeToString,
            ),
            'registrarSalida': grpc.unary_unary_rpc_method_handler(
                    servicer.registrarSalida,
                    request_deserializer=inventario__pb2.RegistrarSalidaRequest.FromString,
                    response_serializer=inventario__pb2.RespuestaExito.SerializeToString,
            ),
            'solicitarDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.solicitarDonaciones,
                    request_deserializer=inventario__pb2.SolicitarDonacionesRequest.FromString,
                    response_serializer=inventario__pb2.SolicitarDonacionesResponse.SerializeToString,
            ),
            'listarSolicitudesExternas': grpc.unary_unary_rpc_method_handler(
                    servicer.listarSolicitudesExternas,
                    request_deserializer=inventario__pb2.ListarSolicitudesExternasRequest.FromString,
                    response_serializer=inventario__pb2.ListarSolicitudesExternasResponse.SerializeToString,
            ),
            'transferirDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.transferirDonacion,
                    request_deserializer=inventario__pb2.TransferirDonacionRequest.FromString,
                    response_serializer=inventario__pb2.RespuestaExito.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.grupog.inventario.InventarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.grupog.inventario.InventarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def crearItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/crearItem',
            inventario__pb2.CrearItemRequest.SerializeToString,
            inventario__pb2.InventarioItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def actualizarItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/actualizarItem',
            inventario__pb2.ActualizarItemRequest.SerializeToString,
            inventario__pb2.InventarioItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def bajaLogicaItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/bajaLogicaItem',
            inventario__pb2.BajaLogicaItemRequest.SerializeToString,
            inventario__pb2.RespuestaExito.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/listarItems',
            inventario__pb2.ListarItemsRequest.SerializeToString,
            inventario__pb2.ListaItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def buscarItemPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/buscarItemPorId',
            inventario__pb2.BuscarItemPorIdRequest.SerializeToString,
            inventario__pb2.InventarioItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registrarSalida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/registrarSalida',
            inventario__pb2.RegistrarSalidaRequest.SerializeToString,
            inventario__pb2.RespuestaExito.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def solicitarDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/solicitarDonaciones',
            inventario__pb2.SolicitarDonacionesRequest.SerializeToString,
            inventario__pb2.SolicitarDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarSolicitudesExternas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/listarSolicitudesExternas',
            inventario__pb2.ListarSolicitudesExternasRequest.SerializeToString,
            inventario__pb2.ListarSolicitudesExternasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def transferirDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.grupog.inventario.InventarioService/transferirDonacion',
            inventario__pb2.TransferirDonacionRequest.SerializeToString,
            inventario__pb2.RespuestaExito.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
